// Code generated by MockGen. DO NOT EDIT.
// Source: internal/api/validator/validator.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	
	gomock "github.com/golang/mock/gomock"
)

// MockEmailValidator is a mock of EmailValidator interface.
type MockEmailValidator struct {
	ctrl     *gomock.Controller
	recorder *MockEmailValidatorMockRecorder
}

// MockEmailValidatorMockRecorder is the mock recorder for MockEmailValidator.
type MockEmailValidatorMockRecorder struct {
	mock *MockEmailValidator
}

// NewMockEmailValidator creates a new mock instance.
func NewMockEmailValidator(ctrl *gomock.Controller) *MockEmailValidator {
	mock := &MockEmailValidator{ctrl: ctrl}
	mock.recorder = &MockEmailValidatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEmailValidator) EXPECT() *MockEmailValidatorMockRecorder {
	return m.recorder
}

// Check mocks base method.
func (m *MockEmailValidator) Check(ctx context.Context, email string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Check", ctx, email)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Check indicates an expected call of Check.
func (mr *MockEmailValidatorMockRecorder) Check(ctx, email interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Check", reflect.TypeOf((*MockEmailValidator)(nil).Check), ctx, email)
}

// Name mocks base method.
func (m *MockEmailValidator) Name() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Name")
	ret0, _ := ret[0].(string)
	return ret0
}

// Name indicates an expected call of Name.
func (mr *MockEmailValidatorMockRecorder) Name() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Name", reflect.TypeOf((*MockEmailValidator)(nil).Name))
}
