// Code generated by MockGen. DO NOT EDIT.
// Source: domain/permission.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/abdallahelassal/UserAuth/domain"
	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
)

// MockPermissionRepository is a mock of PermissionRepository interface.
type MockPermissionRepository struct {
	ctrl     *gomock.Controller
	recorder *MockPermissionRepositoryMockRecorder
}

// MockPermissionRepositoryMockRecorder is the mock recorder for MockPermissionRepository.
type MockPermissionRepositoryMockRecorder struct {
	mock *MockPermissionRepository
}

// NewMockPermissionRepository creates a new mock instance.
func NewMockPermissionRepository(ctrl *gomock.Controller) *MockPermissionRepository {
	mock := &MockPermissionRepository{ctrl: ctrl}
	mock.recorder = &MockPermissionRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPermissionRepository) EXPECT() *MockPermissionRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockPermissionRepository) Create(ctx context.Context, p *domain.Permission) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, p)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockPermissionRepositoryMockRecorder) Create(ctx, p interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockPermissionRepository)(nil).Create), ctx, p)
}

// FindAllPermissions mocks base method.
func (m *MockPermissionRepository) FindAllPermissions(ctx context.Context) ([]domain.Permission, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAllPermissions", ctx)
	ret0, _ := ret[0].([]domain.Permission)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAllPermissions indicates an expected call of FindAllPermissions.
func (mr *MockPermissionRepositoryMockRecorder) FindAllPermissions(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAllPermissions", reflect.TypeOf((*MockPermissionRepository)(nil).FindAllPermissions), ctx)
}

// GetPermissionByRoleIDs mocks base method.
func (m *MockPermissionRepository) GetPermissionByRoleIDs(ctx context.Context, roleID []uuid.UUID) ([]domain.Permission, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPermissionByRoleIDs", ctx, roleID)
	ret0, _ := ret[0].([]domain.Permission)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPermissionByRoleIDs indicates an expected call of GetPermissionByRoleIDs.
func (mr *MockPermissionRepositoryMockRecorder) GetPermissionByRoleIDs(ctx, roleID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPermissionByRoleIDs", reflect.TypeOf((*MockPermissionRepository)(nil).GetPermissionByRoleIDs), ctx, roleID)
}

// GetPermissionsByUserID mocks base method.
func (m *MockPermissionRepository) GetPermissionsByUserID(ctx context.Context, userID uuid.UUID) ([]domain.Permission, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPermissionsByUserID", ctx, userID)
	ret0, _ := ret[0].([]domain.Permission)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPermissionsByUserID indicates an expected call of GetPermissionsByUserID.
func (mr *MockPermissionRepositoryMockRecorder) GetPermissionsByUserID(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPermissionsByUserID", reflect.TypeOf((*MockPermissionRepository)(nil).GetPermissionsByUserID), ctx, userID)
}
