// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/abdallahelassal/UserAuth/internal/usecase (interfaces: RoleUsecase)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	usecase "github.com/abdallahelassal/UserAuth/internal/usecase"
	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
)

// MockRoleUsecase is a mock of RoleUsecase interface.
type MockRoleUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockRoleUsecaseMockRecorder
}

// MockRoleUsecaseMockRecorder is the mock recorder for MockRoleUsecase.
type MockRoleUsecaseMockRecorder struct {
	mock *MockRoleUsecase
}

// NewMockRoleUsecase creates a new mock instance.
func NewMockRoleUsecase(ctrl *gomock.Controller) *MockRoleUsecase {
	mock := &MockRoleUsecase{ctrl: ctrl}
	mock.recorder = &MockRoleUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRoleUsecase) EXPECT() *MockRoleUsecaseMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockRoleUsecase) Create(arg0 context.Context, arg1 usecase.RoleCreateInput) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockRoleUsecaseMockRecorder) Create(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockRoleUsecase)(nil).Create), arg0, arg1)
}

// Delete mocks base method.
func (m *MockRoleUsecase) Delete(arg0 context.Context, arg1 uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockRoleUsecaseMockRecorder) Delete(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockRoleUsecase)(nil).Delete), arg0, arg1)
}

// FindAll mocks base method.
func (m *MockRoleUsecase) FindAll(arg0 context.Context) ([]*usecase.RoleOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAll", arg0)
	ret0, _ := ret[0].([]*usecase.RoleOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAll indicates an expected call of FindAll.
func (mr *MockRoleUsecaseMockRecorder) FindAll(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAll", reflect.TypeOf((*MockRoleUsecase)(nil).FindAll), arg0)
}

// FindByID mocks base method.
func (m *MockRoleUsecase) FindByID(arg0 context.Context, arg1 uuid.UUID) (*usecase.RoleOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", arg0, arg1)
	ret0, _ := ret[0].(*usecase.RoleOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockRoleUsecaseMockRecorder) FindByID(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockRoleUsecase)(nil).FindByID), arg0, arg1)
}

// GetRolesByUserID mocks base method.
func (m *MockRoleUsecase) GetRolesByUserID(arg0 context.Context, arg1 uuid.UUID) ([]*usecase.RoleOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRolesByUserID", arg0, arg1)
	ret0, _ := ret[0].([]*usecase.RoleOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRolesByUserID indicates an expected call of GetRolesByUserID.
func (mr *MockRoleUsecaseMockRecorder) GetRolesByUserID(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRolesByUserID", reflect.TypeOf((*MockRoleUsecase)(nil).GetRolesByUserID), arg0, arg1)
}

// Update mocks base method.
func (m *MockRoleUsecase) Update(arg0 context.Context, arg1 usecase.RoleUpdateInput) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockRoleUsecaseMockRecorder) Update(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockRoleUsecase)(nil).Update), arg0, arg1)
}
