// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/abdallahelassal/UserAuth/internal/usecase (interfaces: PermissionUsecase)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	usecase "github.com/abdallahelassal/UserAuth/internal/usecase"
	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
)

// MockPermissionUsecase is a mock of PermissionUsecase interface.
type MockPermissionUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockPermissionUsecaseMockRecorder
}

// MockPermissionUsecaseMockRecorder is the mock recorder for MockPermissionUsecase.
type MockPermissionUsecaseMockRecorder struct {
	mock *MockPermissionUsecase
}

// NewMockPermissionUsecase creates a new mock instance.
func NewMockPermissionUsecase(ctrl *gomock.Controller) *MockPermissionUsecase {
	mock := &MockPermissionUsecase{ctrl: ctrl}
	mock.recorder = &MockPermissionUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPermissionUsecase) EXPECT() *MockPermissionUsecaseMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockPermissionUsecase) Create(arg0 context.Context, arg1 *usecase.PermissionInput) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockPermissionUsecaseMockRecorder) Create(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockPermissionUsecase)(nil).Create), arg0, arg1)
}

// FindAllPermissions mocks base method.
func (m *MockPermissionUsecase) FindAllPermissions(arg0 context.Context) ([]usecase.PermissionOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAllPermissions", arg0)
	ret0, _ := ret[0].([]usecase.PermissionOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAllPermissions indicates an expected call of FindAllPermissions.
func (mr *MockPermissionUsecaseMockRecorder) FindAllPermissions(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAllPermissions", reflect.TypeOf((*MockPermissionUsecase)(nil).FindAllPermissions), arg0)
}

// GetPermissionByRoleIDs mocks base method.
func (m *MockPermissionUsecase) GetPermissionByRoleIDs(arg0 context.Context, arg1 []uuid.UUID) ([]usecase.GetPermissionsByRoleIDs, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPermissionByRoleIDs", arg0, arg1)
	ret0, _ := ret[0].([]usecase.GetPermissionsByRoleIDs)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPermissionByRoleIDs indicates an expected call of GetPermissionByRoleIDs.
func (mr *MockPermissionUsecaseMockRecorder) GetPermissionByRoleIDs(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPermissionByRoleIDs", reflect.TypeOf((*MockPermissionUsecase)(nil).GetPermissionByRoleIDs), arg0, arg1)
}

// GetPermissionsByUserID mocks base method.
func (m *MockPermissionUsecase) GetPermissionsByUserID(arg0 context.Context, arg1 uuid.UUID) ([]usecase.GetUserPermissions, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPermissionsByUserID", arg0, arg1)
	ret0, _ := ret[0].([]usecase.GetUserPermissions)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPermissionsByUserID indicates an expected call of GetPermissionsByUserID.
func (mr *MockPermissionUsecaseMockRecorder) GetPermissionsByUserID(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPermissionsByUserID", reflect.TypeOf((*MockPermissionUsecase)(nil).GetPermissionsByUserID), arg0, arg1)
}
