// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/abdallahelassal/UserAuth/internal/usecase (interfaces: UserUsecase)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	usecase "github.com/abdallahelassal/UserAuth/internal/usecase"
	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
)

// MockUserUsecase is a mock of UserUsecase interface.
type MockUserUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockUserUsecaseMockRecorder
}

// MockUserUsecaseMockRecorder is the mock recorder for MockUserUsecase.
type MockUserUsecaseMockRecorder struct {
	mock *MockUserUsecase
}

// NewMockUserUsecase creates a new mock instance.
func NewMockUserUsecase(ctrl *gomock.Controller) *MockUserUsecase {
	mock := &MockUserUsecase{ctrl: ctrl}
	mock.recorder = &MockUserUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserUsecase) EXPECT() *MockUserUsecaseMockRecorder {
	return m.recorder
}

// AssignRole mocks base method.
func (m *MockUserUsecase) AssignRole(arg0 context.Context, arg1, arg2 uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AssignRole", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// AssignRole indicates an expected call of AssignRole.
func (mr *MockUserUsecaseMockRecorder) AssignRole(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AssignRole", reflect.TypeOf((*MockUserUsecase)(nil).AssignRole), arg0, arg1, arg2)
}

// FindByID mocks base method.
func (m *MockUserUsecase) FindByID(arg0 context.Context, arg1 uuid.UUID) (*usecase.FindByIDOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", arg0, arg1)
	ret0, _ := ret[0].(*usecase.FindByIDOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockUserUsecaseMockRecorder) FindByID(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockUserUsecase)(nil).FindByID), arg0, arg1)
}

// GetByEmail mocks base method.
func (m *MockUserUsecase) GetByEmail(arg0 context.Context, arg1 string) (*usecase.UserOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByEmail", arg0, arg1)
	ret0, _ := ret[0].(*usecase.UserOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByEmail indicates an expected call of GetByEmail.
func (mr *MockUserUsecaseMockRecorder) GetByEmail(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByEmail", reflect.TypeOf((*MockUserUsecase)(nil).GetByEmail), arg0, arg1)
}

// GetByName mocks base method.
func (m *MockUserUsecase) GetByName(arg0 context.Context, arg1 string) (*usecase.UserOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByName", arg0, arg1)
	ret0, _ := ret[0].(*usecase.UserOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByName indicates an expected call of GetByName.
func (mr *MockUserUsecaseMockRecorder) GetByName(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByName", reflect.TypeOf((*MockUserUsecase)(nil).GetByName), arg0, arg1)
}

// GetFullProfile mocks base method.
func (m *MockUserUsecase) GetFullProfile(arg0 context.Context, arg1 uuid.UUID) (*usecase.FullProfile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFullProfile", arg0, arg1)
	ret0, _ := ret[0].(*usecase.FullProfile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFullProfile indicates an expected call of GetFullProfile.
func (mr *MockUserUsecaseMockRecorder) GetFullProfile(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFullProfile", reflect.TypeOf((*MockUserUsecase)(nil).GetFullProfile), arg0, arg1)
}

// Login mocks base method.
func (m *MockUserUsecase) Login(arg0 context.Context, arg1 usecase.LoginUserInput) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Login", arg0, arg1)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Login indicates an expected call of Login.
func (mr *MockUserUsecaseMockRecorder) Login(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Login", reflect.TypeOf((*MockUserUsecase)(nil).Login), arg0, arg1)
}

// Signup mocks base method.
func (m *MockUserUsecase) Signup(arg0 context.Context, arg1 usecase.CreateUserInput) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Signup", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Signup indicates an expected call of Signup.
func (mr *MockUserUsecaseMockRecorder) Signup(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Signup", reflect.TypeOf((*MockUserUsecase)(nil).Signup), arg0, arg1)
}
