// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/abdallahelassal/UserAuth/internal/usecase (interfaces: EmailUsecase)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/abdallahelassal/UserAuth/domain"
	gomock "github.com/golang/mock/gomock"
)

// MockEmailUsecase is a mock of EmailUsecase interface.
type MockEmailUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockEmailUsecaseMockRecorder
}

// MockEmailUsecaseMockRecorder is the mock recorder for MockEmailUsecase.
type MockEmailUsecaseMockRecorder struct {
	mock *MockEmailUsecase
}

// NewMockEmailUsecase creates a new mock instance.
func NewMockEmailUsecase(ctrl *gomock.Controller) *MockEmailUsecase {
	mock := &MockEmailUsecase{ctrl: ctrl}
	mock.recorder = &MockEmailUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEmailUsecase) EXPECT() *MockEmailUsecaseMockRecorder {
	return m.recorder
}

// Validate mocks base method.
func (m *MockEmailUsecase) Validate(arg0 context.Context, arg1 string) domain.ValidationResult {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Validate", arg0, arg1)
	ret0, _ := ret[0].(domain.ValidationResult)
	return ret0
}

// Validate indicates an expected call of Validate.
func (mr *MockEmailUsecaseMockRecorder) Validate(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Validate", reflect.TypeOf((*MockEmailUsecase)(nil).Validate), arg0, arg1)
}
