// Code generated by MockGen. DO NOT EDIT.
// Source: domain/personal_access_token.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/abdallahelassal/UserAuth/domain"
	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
)

// MockPersonalAccessTokenRepository is a mock of PersonalAccessTokenRepository interface.
type MockPersonalAccessTokenRepository struct {
	ctrl     *gomock.Controller
	recorder *MockPersonalAccessTokenRepositoryMockRecorder
}

// MockPersonalAccessTokenRepositoryMockRecorder is the mock recorder for MockPersonalAccessTokenRepository.
type MockPersonalAccessTokenRepositoryMockRecorder struct {
	mock *MockPersonalAccessTokenRepository
}

// NewMockPersonalAccessTokenRepository creates a new mock instance.
func NewMockPersonalAccessTokenRepository(ctrl *gomock.Controller) *MockPersonalAccessTokenRepository {
	mock := &MockPersonalAccessTokenRepository{ctrl: ctrl}
	mock.recorder = &MockPersonalAccessTokenRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPersonalAccessTokenRepository) EXPECT() *MockPersonalAccessTokenRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockPersonalAccessTokenRepository) Create(ctx context.Context, hash *domain.PersonalAccessToken) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, hash)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockPersonalAccessTokenRepositoryMockRecorder) Create(ctx, hash interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockPersonalAccessTokenRepository)(nil).Create), ctx, hash)
}

// Delete mocks base method.
func (m *MockPersonalAccessTokenRepository) Delete(ctx context.Context, hash string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, hash)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockPersonalAccessTokenRepositoryMockRecorder) Delete(ctx, hash interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockPersonalAccessTokenRepository)(nil).Delete), ctx, hash)
}

// DeleteByUserID mocks base method.
func (m *MockPersonalAccessTokenRepository) DeleteByUserID(ctx context.Context, userID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByUserID", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteByUserID indicates an expected call of DeleteByUserID.
func (mr *MockPersonalAccessTokenRepositoryMockRecorder) DeleteByUserID(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByUserID", reflect.TypeOf((*MockPersonalAccessTokenRepository)(nil).DeleteByUserID), ctx, userID)
}

// FindByToken mocks base method.
func (m *MockPersonalAccessTokenRepository) FindByToken(ctx context.Context, hash string) (*domain.PersonalAccessToken, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByToken", ctx, hash)
	ret0, _ := ret[0].(*domain.PersonalAccessToken)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByToken indicates an expected call of FindByToken.
func (mr *MockPersonalAccessTokenRepositoryMockRecorder) FindByToken(ctx, hash interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByToken", reflect.TypeOf((*MockPersonalAccessTokenRepository)(nil).FindByToken), ctx, hash)
}

// UpdateLastUseAt mocks base method.
func (m *MockPersonalAccessTokenRepository) UpdateLastUseAt(ctx context.Context, token string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateLastUseAt", ctx, token)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateLastUseAt indicates an expected call of UpdateLastUseAt.
func (mr *MockPersonalAccessTokenRepositoryMockRecorder) UpdateLastUseAt(ctx, token interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateLastUseAt", reflect.TypeOf((*MockPersonalAccessTokenRepository)(nil).UpdateLastUseAt), ctx, token)
}
